version: "2"

run:
  tests: true

issues:
  max-issues-per-linter: 100
  max-same-issues: 100

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax

linters:
  default: standard
  enable:
    # Bug catchers
    - bodyclose
    - contextcheck
    - durationcheck
    - makezero
    - nilerr
    - nilnesserr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    # Code quality
    - errname
    - gocritic
    - mirror
    - reassign
    - recvcheck
    - revive
    - unconvert
    - unparam
    - wastedassign
    # Modernization
    - copyloopvar
    - exptostd
    - intrange
    - modernize
    - usetesting
    # Security
    - gosec
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: .*_test\.go$
      - linters:
          - gocritic
        text: "^exitAfterDefer: .*"
        path: .*_test\.go$
      - linters:
          - gosec
        text: "^G304: .*"
        path: .*_test\.go$
      - linters:
          - gosec
        text: "^G404: .*"
        path: .*_test\.go$
  settings:
    staticcheck:
      checks:
        - -QF1010 # could convert argument to string
    gosec:
      # TODO: Enable all gosec rules
      excludes:
        - G103 # Use of unsafe calls should be audited
        - G115 # integer overflow conversion int -> int32
    revive:
      rules:
        - name: package-comments
          disabled: true
